### ISSUE TITLE
Week 3 Out of Class Work : Review Online Presentations

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/f2019_team-4#12]
[https://app.box.com/s/kge844rxwqn44hsugmvzagfkbalwvz6p](https://app.box.com/s/kge844rxwqn44hsugmvzagfkbalwvz6p)

**Comment by rgrossman7** [comment]
I've reviewed the online presentations @IITIDIDX597/f2019_team-4 @hellogoeuny @xguo29 @xtang11

**Comment by rgrossman7** [comment]
All presentations reviewed
- [x] @rgrossman7 
- [ ] @xguo29 
- [ ] @xtang11 
- [x] @hellogoeuny 

Last one to check their box please move the job to done in Kanban.
