### ISSUE TITLE
[Guest]Better control of what I'm sharing

### ISSUE THREAD

**Issue by xguo29** [IITIDIDX597/f2019_team-4#35]
**As a guest**, **I want**Abby to give me a distinct prompt when it starts to record my voice, and also provide me with the option to choose how I want it to be shared (share it with the public or keep it to certain people or keep it to my self) **so that** I can have control of what I'm sharing.

Sub-hill of hill3
Abby can not record voices without a distinct prompt.

**Comment by hellogoeuny** [comment]
Hi @xguo29 !
I'd like to add more value and slightly simplify the story. I am suggesting;

**As a** guest, **I want to** have a distinctive cue to be notified that when my voice is recorded **so that** I can own sharing permission for my privacy.

**Comment by hellogoeuny** [comment]
**As a** guest, **I want to** have a distinctive cue to be notified that when my voice is recorded **so that** I have control of contents and people I share with.

**Comment by akallish** [comment]
@hellogoeuny good iteration. How about this one:
@rgrossman7 @xguo29 @xtang11

> **As a** guest
> **I want to** have distinctive feedback from Abby to let me know when my voice is recorded 
> **So that** I can then share the recording with others

**Comment by xguo29** [comment]
@hellogoeuny @akallish good feedbacks, thanks a lot! 

In the beginning, I actually try to combine two stories into one, one is about having sharing permission(as all the feedbacks currently focused on), another one is about the reception scope, guest can choose to share it 1.with the public, 2.share it with certain people, 3.keep it to myself.

I guess I can modify this one based on your feedback, and create a new story if it's worth capturing.

**Comment by rgrossman7** [comment]
@hellogoeuny @akallish would it make more sense to break that into more than one story?

**Comment by rgrossman7** [comment]
As a bigtime Instagram influencer, I want to know when Abby is about to start recording my voice so that I know when to start talking to sound my best for everybody.

> **As a** guest, **I want to** have a distinctive cue to be notified that when my voice is recorded **so that** I have control of contents and people I share with.

**Comment by rgrossman7** [comment]
I'm going to break into two stories:

As a big-time Instagram influencer visiting Chicago, I want to be able to share my super awesome witty review of the Airbnb that I left on Abby with my adoring public.



> **As a guest**, **I want**Abby to give me a distinct prompt when it starts to record my voice, and also provide me with the option to choose how I want it to be shared (share it with the public or keep it to certain people or keep it to my self) **so that** I can have control of what I'm sharing.
> 
> Sub-hill of hill3
> Abby can not record voices without a distinct prompt.

**Comment by akallish** [comment]
@rgrossman7 @xguo29 Here are two stories. Let me know if these iterations make sense and map to your intent based on the sub-hill:

> **As a guest**
> **I want** Abby to give me a distinct prompt when it starts to record my voice, and also provide me with the option to choose how I want it to be shared (three options : share it with the public; keep it to certain people; or keep it to myself) 
> **so that** I can have control of what I'm sharing with others.

As for the Instagram influencer story, it really does not make sense to me. Is it about a sound test which can be redone if a user does not like the results?

**Comment by rgrossman7** [comment]
@akallish it's about a prompt.  Are you planning on doing all of our iterations for us?

**Comment by akallish** [comment]
@rgrossman7 just trying to help. I will step back. Thanks for your question.

**Comment by hellogoeuny** [comment]
**Acceptance Criteria**

**Given** I am a guest and I want to share my travel recommendation with other travelers  
**When** I ask Abby to record my voice by saying " Hey! Abby, Record me!"
**Then** Abby makes a red light signal to show the recording process. 

> As a guest
> I want to have distinctive feedback from Abby to let me know when my voice is recorded
> So that I can have a better sense of the content that I am sharing.

**Comment by hellogoeuny** [comment]
This is an iteration:

**Given** I am a guest and I am conscious about my personal information shared  
**When** I attempt to leave my recommendations or other personal experiences related to my trips
**Then** Abby sends a notification and lets me know my voice is now recorded.

**Comment by rgrossman7** [comment]
Another iteration:

**Given** I am a guest and I am interested in recording a message 
**When** I am using Abby
**Then** Abby will make a red light signal and a beep to let me know recording is about to start

**Comment by xtang11** [comment]
Another Iteration:

**Given** I am a guest and I am using Abby to record my travel recommendations,
**When** I finish my sharing by telling Abby "I am done with the sharing",
**Then** Abby plays what it records as my recommendation to ask my final confirmation to upload it to the cloud. 

> **As a** guest
> **I want** to have distinctive feedback from Abby to let me know when my voice is recorded
> **So that** I can have a better sense of the content that I am sharing.

**Comment by akallish** [comment]
@xtang11 @rgrossman7 @hellogoeuny All three acceptance criteria are good and clear. 

Based on the last story iteration:
**As a** guest
**I want** Abby to give me a distinct prompt when it starts to record my voice, and also provide me with the option to choose how I want it to be shared (three options : share it with the public; keep it to certain people; or keep it to myself)
**So that** I can have control of what I'm sharing with others.

The acceptance criteria needs to directly address the want and so that. @rgrossman7 is closest, but the system has to provide who the recording can be shared with.

**Comment by xtang11** [comment]
@akallish We separate the original story

> As a guest,
> I want Abby to give me a distinct prompt when it starts to record my voice, and also provide me with the option to choose how I want it to be shared (three options : share it with the public; keep it to certain people; or keep it to myself),
> so that I can have control of what I'm sharing with others.

into 2: 
1. **As a** guest, **I want** Abby to give me a distinct prompt when it starts to record my voice, **so that** I can have a better control over the content I am being recorded and may share in the future.
2. **As a** guest, **I want** Abby to provide me with the options to choose how I want my recordings to be shared (three options : share it with the public; keep it to certain people; or keep it to myself), **so that** I can have better sense of control over whom I am sharing to.

And we choose 1 to create acceptance criteria. Sorry for any confusion last time.

**Comment by xtang11** [comment]
And we will accept @rgrossman7 's acceptance criteria as closest one:

> Given I am a guest and I am interested in recording a message
> When I am using Abby
> Then Abby will make a red light signal and a beep to let me know recording is about to start
